### ISSUE TITLE
[FRONTEND] login page forgot password

### ISSUE THREAD

**Issue by Jcjacky** [fsxfreak/club-suite#162]
We need to remove the "Forgot password" button if we are not implementing it.

**Comment by Jcjacky** [comment]
We can change this button to the "About" button, since users will want to know what this website is about before signing up.

I think all other pages need user to be logged in before viewing, otherwise it will redirect to the Login page. If we can remove this "login" requirement from the "About" page, then we can let the user view the about page, then if they click any other page, it will just redirect them back to the login page.

**Comment by AftermathK** [comment]
But we should still allow the user to regain access to their account somehow
