### ISSUE TITLE
[FRONTEND & BACKEND] Confirmation message when managing the club_roster

### ISSUE THREAD

**Issue by PKpinkuro** [fsxfreak/club-suite#213]
- Message when owner cannot resign in "manage my clubs" because there is only 1 owner in the club.

**Comment by ShijieFan** [comment]
Added confirm popups when deleting/promoting/demoting members. I don't know how to display the cannot resign message though...

**Comment by kevinzavier** [comment]
I added some error messaging for demoting ureself

**Comment by stonecoldnicole** [comment]
@ShijieFan @kevinzavier this is super legit!! Great work!!
