### ISSUE TITLE
[FRONTEND] [BACKEND] Browse All Clubs

### ISSUE THREAD

**Issue by stonecoldnicole** [fsxfreak/club-suite#224]
Frontend: add a button (or just a link) to the search page that lets the user browse all clubs in the system.

Backend: will need to query the database for all clubs and sort by alphabetical ordering.

**Comment by AftermathK** [comment]
what if we just display a list of all of the clubs on the search page. However, we may want to set a limit on the number of clubs that we display.

**Comment by kevinzavier** [comment]
Delete [:4]

**Comment by kevinzavier** [comment]
I set a limit

**Comment by AftermathK** [comment]
which branch are you working on?

**Comment by kevinzavier** [comment]
i pushed to master, but im working on something else that allows so if the user click on the club, it displays the picture of the club

**Comment by stonecoldnicole** [comment]
Do you mean if they search and then click on the picture for a club it brings them to that club's page? Because if so, that would be wonderful! That is one of my only usability complaints that is outstanding at this point.

**Comment by kevinzavier** [comment]
right now this link is on the club title, so u want it on the picture?
