### ISSUE TITLE
[FRONTEND] /[BACKEND] add revenue column to budgets

### ISSUE THREAD

**Issue by Jcjacky** [fsxfreak/club-suite#228]
Right now, we in the table, we have Event Name and Event Cost. 

It would be nice to also have a Event Revenue column and change the Event Cost numbers from Positive to Negative, so 50 is actually -50.

In view_events.py, this was used to calculate the event revenue:

`
# getting the revnue
    eventSignIns = EventSignIn.objects.filter(eid=event_id, status=True)
    totalCost = 0
    i = 1
    for eventSignIn in eventSignIns:
        totalCost = i * eventSignIn.eid.event_fee
        i+=1
`

Instead of the for loop, maybe this will work:
`eventSignIns = EventSignIn.objects.filter(eid=event_id, status=True)
totalCost=len(eventSignIns)*eventSignIn.eid.event_fee`

**Comment by fsxfreak** [comment]
fixed the code, won't add anything to the event model. it's too late
