### ISSUE TITLE
[QUESTION] Budget expiration date

### ISSUE THREAD

**Issue by Jcjacky** [fsxfreak/club-suite#229]
what happens after a budget expires? does it get removed? Because that would be problematic in calculating event costs (One day you are under-budget, the next, you are over...)

**Comment by stonecoldnicole** [comment]
@arangama I was wondering how you currently handle this within your organizations? Do you have any suggestions for what we should do here?

**Comment by arangama** [comment]
In general, from my experience, a budget is created in the beginning of the school year and is only updated about once every year! Sometimes it can updated be during the school year, but that's only for very minor adjustments. After the end date (which is almost always the school year) has passed, then yes the item should be removed from the budget. In terms of our project testing, I don't think it should be a huge issue. I feel we can simply specify the exact dates to enter in our test plan.
