### ISSUE TITLE
[BACKEND] [QUESTION] Budget Not Saving

### ISSUE THREAD

**Issue by stonecoldnicole** [fsxfreak/club-suite#235]
Currently, I am filling in values for my club budget and it is not saving the information anywhere. Do you know if there is a reason for this? Or is this a bug that needs to be resolved? Feel free to pass this ticket along if you think it is in someone else's domain.
![budget](https://cloud.githubusercontent.com/assets/25188090/23780832/053e80d2-04fe-11e7-84e9-b21922c25117.JPG)

**Comment by Jcjacky** [comment]
start/end date cannot be in the past. There should be an error message, it should be the same error as create events.

**Comment by stonecoldnicole** [comment]
Ok thanks for clarifying. There is no error message being displayed currently.

**Comment by fsxfreak** [comment]
fixing division name uniqueness constraint required altering the Division model. therefore divisions, budgets, events, and eventsignins are all invalidated.  please do the following commands

`python3 manage.py makemigrations suite`
`python3 manage.py migrate suite`
`python3 manage.py dbshell`
`DELETE FROM suite_division;`
`DELETE FROM suite_budget;`
`DELETE_FROM suite_event;`
`DELETE_FROM suite_eventsignin;
