### ISSUE TITLE
[FRONTEND] Maybe change Bulma INFO Color to be more lighter? I think it looks too similiar to SUCCESS and Primary

### ISSUE THREAD

**Issue by kevinzavier** [fsxfreak/club-suite#237]
I think we should change the bulma notification colors, as in -primary, -info, and -success so they are more differentiable? Like when someone sends a club join request, i think the notification color should be a little lighter

**Comment by stonecoldnicole** [comment]
There are a lot of little color changes that I would like to make. I ran into some trouble trying to adjust that periwinkle color, as it seems Bulma is calculating it off of something and I need to spend some more time troubleshooting the cause.
![capture](https://cloud.githubusercontent.com/assets/25188090/23818145/6a1c5eb6-05ad-11e7-86cb-e6a9d9f76f28.JPG)
