### ISSUE TITLE
Submit Buttons

### ISSUE THREAD

**Issue by stonecoldnicole** [fsxfreak/club-suite#242]
The submit buttons should be rendered to the bottom right of the input box (see the "Comment" button on this page for reference). These pages are affected, hopefully I get them all here:

Create Club
Account (both save buttons)
Generate Email List (Copy Emails)
Access Budget --> Manage Logistics (two submit buttons)
Create Event

![submit](https://cloud.githubusercontent.com/assets/25188090/23818284/b485342c-05ae-11e7-9ace-7812a2b80ece.JPG)

**Comment by ShijieFan** [comment]
Account (both save buttons)
