### ISSUE TITLE
[BACKEND] [FRONTEND] Notifications

### ISSUE THREAD

**Issue by stonecoldnicole** [fsxfreak/club-suite#244]
Notifications are not displaying for club roster anymore. Ugly notifications are better than no notifications. Please revert changes or make pretty ones, but we need something... Please and thank you! https://drive.google.com/file/d/0B-abbIQx8fzJSHJkdWJ3Vm1tRTg/view?usp=sharing

**Comment by kevinzavier** [comment]
I did the copying messages, look at view_club_create and club_view.html to use messages. And alerts dont qualify as notifications...

**Comment by ShijieFan** [comment]
I do think there needs have some confirmation dialog before owner does anything with the members though...Is there an alternative to alert? I never worked with frontend stuff before so I have no idea...

**Comment by kevinzavier** [comment]
Yes there is! Use JavaScript and bulma modals. PLEASE don't make Leon do this, he's literally done everything else

**Comment by fsxfreak** [comment]
something like this lol
https://github.com/fsxfreak/club-suite/blob/24a7daed98742d71c7d66aff5f7f27540c418eec/clubsuite/suite/static/javascript/club_manage.js
https://github.com/fsxfreak/club-suite/blob/24a7daed98742d71c7d66aff5f7f27540c418eec/clubsuite/suite/templates/dashboard/club_manage.html#L41

**Comment by fsxfreak** [comment]
lookin good
