### ISSUE TITLE
[FRONTEND] No default club/event image, looks like a broken link

### ISSUE THREAD

**Issue by LeoTheG** [fsxfreak/club-suite#265]

**Comment by stonecoldnicole** [comment]
I think it might be better/easier to prevent a submission from being accepted unless they have uploaded a photo.

**Comment by LeoTheG** [comment]
Might be better to reinclude the default photo from the previous versions. We shouldn't force the user to upload a photo imo

**Comment by kevinzavier** [comment]
leon fixed it on the liveserver
